src/Entity/Thread.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\CreatedAtTrait;
use App\Entity\Traits\PrimaryKeyTrait;
use App\Repository\ThreadRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ThreadRepository::class)]
#[UniqueEntity('slug')]
class Thread
{
    use CreatedAtTrait;
    use PrimaryKeyTrait;

    final public const TITLE_MIN_LENGTH = 12;
    final public const TITLE_MAX_LENGTH = 50;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?string $title = null;

    #[Gedmo\Slug(fields: ['title'])]
    #[ORM\Column(unique: true)]
    private ?string $slug = null;

    #[Gedmo\Blameable(on: 'create')]
    #[ORM\ManyToOne(inversedBy: 'threads')]
    private ?User $author = null;

    #[ORM\ManyToOne(inversedBy: 'threads')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotNull]
    private ?Forum $forum = null;

    #[ORM\Column]
    #[Assert\NotNull]
    private bool $isLock = false;

    #[ORM\Column]
    #[Assert\NotNull]
    private bool $isPin = false;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Message $lastMessage = null;

    #[ORM\OneToMany(mappedBy: 'thread', targetEntity: Message::class, orphanRemoval: true)]
    private Collection $messages;

    #[ORM\Column(type: 'smallint')]
    private int $totalMessages = 0;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getForum(): ?Forum
    {
        return $this->forum;
    }

    public function setForum(?Forum $forum): self
    {
        $this->forum = $forum;

        return $this;
    }

    public function isLock(): bool
    {
        return $this->isLock;
    }

    public function setLock(bool $isLock): self
    {
        $this->isLock = $isLock;

        return $this;
    }

    public function isPin(): bool
    {
        return $this->isPin;
    }

    public function setPin(bool $isPin): self
    {
        $this->isPin = $isPin;

        return $this;
    }

    public function getLastMessage(): ?Message
    {
        return $this->lastMessage;
    }

    public function setLastMessage(?Message $lastMessage): self
    {
        $this->lastMessage = $lastMessage;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setThread($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getThread() === $this) {
                $message->setThread(null);
            }
        }

        return $this;
    }

    public function getTotalMessages(): ?int
    {
        return $this->totalMessages;
    }

    public function getTotalAnswers(): ?int
    {
        return $this->totalMessages - 1;
    }

    public function incrementTotalMessages(): self
    {
        ++$this->totalMessages;

        return $this;
    }

    public function decrementTotalMessages(): self
    {
        --$this->totalMessages;

        return $this;
    }
}

src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\CreatedAtTrait;
use App\Entity\Traits\PrimaryKeyTrait;
use App\Repository\UserRepository;
use App\ValueObject\Locales;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Stringable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity('pseudo')]
#[UniqueEntity('email')]
#[UniqueEntity('slug')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, Stringable
{
    use CreatedAtTrait;
    use PrimaryKeyTrait;

    final public const PSEUDO_MIN_LENGTH = 3;
    final public const PSEUDO_MAX_LENGTH = 10;

    #[ORM\Column(unique: true)]
    #[Assert\Regex(pattern: '#^[a-z0-9]+$#i', message: 'Your pseudo can only contains letters (a-z) and numbers.')]
    #[Assert\Length(min: self::PSEUDO_MIN_LENGTH, max: self::PSEUDO_MAX_LENGTH, minMessage: 'Your pseudo must be at least {{ limit }} characters', maxMessage: 'Your pseudo must not exceed {{ limit }} characters')]
    private ?string $pseudo = null;

    #[Gedmo\Slug(fields: ['pseudo'])]
    #[ORM\Column(unique: true, nullable: false)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?string $hash = null;

    #[ORM\Column(unique: true, nullable: false)]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    #[ORM\Column(nullable: true)]
    protected ?DateTime $lastActivityAt = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Thread::class)]
    private Collection $threads;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Message::class)]
    private Collection $messages;

    #[ORM\OneToMany(mappedBy: 'updatedBy', targetEntity: Message::class)]
    private Collection $updatedMessages;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: MessageLike::class, orphanRemoval: true)]
    private Collection $likes;

    #[ORM\OneToMany(mappedBy: 'reportedBy', targetEntity: Report::class)]
    private Collection $reports;

    #[ORM\OneToMany(mappedBy: 'treatedBy', targetEntity: Report::class)]
    private Collection $treatedReports;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull]
    #[Assert\Choice(callback: 'getLocales')]
    #[Assert\Language]
    private ?string $locale = Locales::DEFAULT;

    public function __construct()
    {
        $this->threads = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->pseudo;
    }

    public function isActiveNow(): bool
    {
        return $this->getLastActivityAt() > new DateTime('5 minutes ago');
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getLastActivityAt(): ?DateTime
    {
        return $this->lastActivityAt;
    }

    public function setLastActivityAt(DateTime $lastActivityAt): self
    {
        $this->lastActivityAt = $lastActivityAt;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param string[] $roles
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->hash;
    }

    public function eraseCredentials(): void {}

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @return Collection|Thread[]
     */
    public function getThreads(): Collection
    {
        return $this->threads;
    }

    public function addThread(Thread $thread): self
    {
        if (!$this->threads->contains($thread)) {
            $this->threads[] = $thread;
            $thread->setAuthor($this);
        }

        return $this;
    }

    public function removeThread(Thread $thread): self
    {
        if ($this->threads->removeElement($thread)) {
            // set the owning side to null (unless already changed)
            if ($thread->getAuthor() === $this) {
                $thread->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setAuthor($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getAuthor() === $this) {
                $message->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[];
     */
    public function getUpdatedByMessages(): Collection
    {
        return $this->updatedMessages;
    }

    /**
     * @return Collection|MessageLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(MessageLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(MessageLike $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Report[]
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    /**
     * @return Collection|Report[]
     */
    public function getTreatedReports(): Collection
    {
        return $this->treatedReports;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public static function getLocales(): array
    {
        return array_keys(Locales::AVAILABLE);
    }
}

src/Controller/UserController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;
use App\Form\UserSettingsType;
use App\Repository\MessageRepository;
use App\Repository\ThreadRepository;
use App\ValueObject\Locales;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route(name: 'user.')]
class UserController extends AbstractBaseController
{
    #[Route(path: '/user/{slug}', name: 'profile', methods: ['GET'])]
    public function profile(User $user, ThreadRepository $threadRepository, MessageRepository $messageRepository): Response
    {
        return $this->render('user/profile.html.twig', [
            'user' => $user,
            'lastThreads' => $threadRepository->findLastThreadsByUser($user, 5),
            'lastMessages' => $messageRepository->findLastMessagesByUser($user, 5),
        ]);
    }

    #[Route(path: '/user/{slug}/threads', name: 'threads', methods: ['GET'])]
    public function threads(User $user, ThreadRepository $threadRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $threadRepository->findThreadsByUserQb($user),
            $request->query->getInt('page', 1),
            25
        );

        return $this->render('user/threads.html.twig', [
            'user' => $user,
            'pagination' => $pagination,
        ]);
    }

    #[Route(path: '/user/{slug}/messages', name: 'messages', methods: ['GET'])]
    public function messages(User $user, MessageRepository $messageRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $messageRepository->findMessagesByUserQb($user),
            $request->query->getInt('page', 1),
            25
        );

        return $this->render('user/messages.html.twig', [
            'user' => $user,
            'pagination' => $pagination,
        ]);
    }

    #[Route(path: '/change-locale', name: 'locale', methods: 'GET')]
    public function locale(Request $request, EntityManagerInterface $em): RedirectResponse
    {
        $newLocale = $request->getSession()->get('_locale') === Locales::ENGLISH ? Locales::FRENCH : Locales::ENGLISH;

        if ($user = $this->getUser()) {
            $user->setLocale($newLocale);
            $em->flush();
        }

        $request->getSession()->set('_locale', $newLocale);

        return $this->redirectToReferer($request);
    }

    #[Route(path: '/settings', name: 'settings', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function settings(Request $request, EntityManagerInterface $em): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        $form = $this->createForm(UserSettingsType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            if (($userLocale = $user->getLocale()) && $userLocale !== $request->getSession()->get('_locale', Locales::DEFAULT)) {
                $request->getSession()->set('_locale', $userLocale);
            }

            return $this->redirectToRoute('user.settings');
        }

        return $this->renderForm('user/settings.html.twig', [
            'user' => $this->getUser(),
            'form' => $form,
        ]);
    }
}

templates/user/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Connexion - Forums{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-md-center mt-5">
            <h1>Connexion</h1>
            <div class="col col-lg-12 col-md-12 col-sm-12">
                <form action="{{ path('user.login') }}" method="post">
                    {% if error %}
                        <div class="alert alert-danger">Identifiants incorrects !</div>
                    {% endif %}
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="_username" class="form-control" id="email" placeholder="Votre email"
                               value="{{ last_username }}">
                    </div>
                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <input type="password" name="_password" class="form-control" id="password"
                               placeholder="Votre mot de passe">
                    </div>
                    <div class="form-check mb-3">
                        <input type="checkbox" class="form-check-input" id="_remember_me" name="_remember_me">
                        <label class="form-check-label" for="_remember_me">Se souvenir de moi</label>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Connexion</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/messages.html.twig
{% extends 'layouts/full-width.html.twig' %}

{% block title %}{{ app.user == user ? 'My messages'|trans : 'Profile of %user% : messages'|trans({'%user%': user}) }}{% endblock %}

{% block content %}
    {% do append_breadcrumb('Members'|trans, path('page.members')) %}
    {% do append_breadcrumb(user.pseudo, path('user.profile', {'slug': user.slug})) %}
    {% do append_breadcrumb('Published messages'|trans) %}

    {{ include('partials/_breadcrumb.html.twig') }}

    <div class="row">
        <div class="col col-lg-12 col-md-12 col-sm-12">
            <h3>{{ user }}
                - {{ user.messages|length }} {{ user.messages|length <= 1 ? 'published message'|trans : 'published messages'|trans }}</h3>

            {% if pagination.getTotalItemCount > 0 %}
                <table class="table table-hover table-sm">
                    <thead>
                    <tr>
                        <th scope="col" style="width: 20%">{% trans %}Published on{% endtrans %}</th>
                        <th scope="col" style="width: 35%">{% trans %}Content{% endtrans %}</th>
                        <th scope="col" style="width: 45%">{% trans %}Thread{% endtrans %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for message in pagination %}
                        <tr>
                            <td>
                                <a href="{{ path('message.show', {'uuid': message.uuidBase32}) }}">{{ message.createdAt|ago }}</a>
                            </td>
                            <td>{{ message.content|striptags|u.truncate(45, '...', false) }}</td>
                            <td>
                                <a href="{{ path('thread.show', {'slug': message.thread.slug}) }}">{{ message.thread.title }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {{ knp_pagination_render(pagination) }}
            {% else %}
                {% trans %}This user has not yet posted a message{% endtrans %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/user/profile.html.twig
{% extends 'layouts/full-width.html.twig' %}

{% block title %}{{ app.user == user ? 'My profile'|trans : 'Profile of %user%'|trans({'%user%': user}) }}{% endblock %}

{% set role = user_profile_role(user) %}

{% block content %}
    {% do append_breadcrumb('Members'|trans, path('page.members')) %}
    {% do append_breadcrumb(user.pseudo) %}

    {{ include('partials/_breadcrumb.html.twig') }}

    <div class="row">
        <div class="col col-lg-12 col-md-12 col-sm-12">
            <h3>
                <span>{{ user }}</span>
                {% if is_granted('ROLE_MODERATOR') %}
                    <a class="btn btn-warning btn-sm" href="{{ path('admin.user.details', {'slug': user.slug}) }}" title="{% trans %}Admin{% endtrans %}">
                        <i class="fas fa-user"></i> {% trans %}Admin{% endtrans %}
                    </a>
                {% endif %}
            </h3>
            <p>
                {% if role %}
                    <strong class="text-danger">{{ role }}</strong><br>
                {% endif %}

                {% trans %}Registration date{% endtrans %} : {{ user.createdAt|format_datetime('medium', 'none') }}
                {% if user.lastActivityAt %}
                    <br>{% trans %}Last activity{% endtrans %} : {{ user.lastActivityAt|format_datetime }}
                {% endif %}
                <br> {% trans %}Total messages{% endtrans %} : {{ user.messages|length }}
            </p>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col col-lg-6 col-md-6 col-sm-6">
            <h4>{% trans %}Latest threads created{% endtrans %}</h4>
            {% if lastThreads|length > 0 %}
                <ul>
                    {% for thread in lastThreads %}
                        <li>
                            <a href="{{ path('thread.show', {'slug': thread.slug}) }}">{{ thread.title|u.truncate(50, '...', false) }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <a href="{{ path('user.threads', {'slug': user.slug}) }}">{{ app.user == user ? 'See my threads'|trans : 'See all the threads created by %user%'|trans({'%user%': user}) }}</a>
            {% else %}
                {% trans %}This user has not yet created a thread{% endtrans %}
            {% endif %}
        </div>

        <div class="col col-lg-6 col-md-6 col-sm-6">
            <h4>{% trans %}Last participations{% endtrans %}</h4>
            {% if lastMessages|length > 0 %}
                <ul>
                    {% for message in lastMessages %}
                        <li>
                            <a href="{{ path('message.show', {'uuid': message.uuidBase32}) }}">{{ message.content|striptags|u.truncate(50, '...', false) }}
                        </li>
                    {% endfor %}
                </ul>
                <a href="{{ path('user.messages', {'slug': user.slug}) }}">{{ app.user == user ? 'See my participations'|trans : 'See all the participations of %user%'|trans({'%user%': user}) }}</a>
            {% else %}
                {% trans %}This user has not yet posted a message{% endtrans %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/user/settings.html.twig
{% extends 'layouts/full-width.html.twig' %}

{% block title %}{% trans %}Settings{% endtrans %}{% endblock %}

{% block content %}
    {% do append_breadcrumb('Members'|trans, path('page.members')) %}
    {% do append_breadcrumb(user.pseudo, path('user.profile', {'slug': user.slug})) %}
    {% do append_breadcrumb('My settings'|trans) %}

    {{ include('partials/_breadcrumb.html.twig') }}

    <div class="row">
        <div class="col col-lg-3 col-md-3 col-sm-3">
            {{ include('partials/_simple_form.twig') }}
        </div>
    </div>
{% endblock %}

templates/user/threads.html.twig
{% extends 'layouts/full-width.html.twig' %}

{% block title %}{{ app.user == user ? 'My threads'|trans : 'Profile of %user% : threads'|trans({'%user%': user}) }}{% endblock %}

{% block content %}
    {% do append_breadcrumb('Members'|trans, path('page.members')) %}
    {% do append_breadcrumb(user.pseudo, path('user.profile', {'slug': user.slug})) %}
    {% do append_breadcrumb('Created threads'|trans) %}

    {{ include('partials/_breadcrumb.html.twig') }}

    <div class="row">
        <div class="col col-lg-12 col-md-12 col-sm-12">
            <h3>{{ user }}
                - {{ user.threads|length }} {{ user.threads|length <= 1 ? 'created thread'|trans : 'created threads'|trans }}</h3>

            {% if pagination.getTotalItemCount > 0 %}
                <table class="table table-hover table-sm">
                    <thead>
                    <tr>
                        <th scope="col">{% trans %}Thread{% endtrans %}</th>
                        <th scope="col">{% trans %}Total answers{% endtrans %}</th>
                        <th scope="col">{% trans %}Last message{% endtrans %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for thread in pagination %}
                        <tr>
                            <td><a href="{{ path('thread.show', {'slug': thread.slug}) }}">{{ thread.title }}</a></td>
                            <td>{{ thread.totalAnswers }}</td>
                            <td>
                                <a href="{{ path('message.show', {'uuid': thread.lastMessage.uuidBase32}) }}">{{ thread.lastMessage.createdAt|ago }}</a>
                                {% trans %}by{% endtrans %} {{ user_profile_link(thread.lastMessage.author) }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {{ knp_pagination_render(pagination) }}
            {% else %}
                This user has not yet created a thread
            {% endif %}
        </div>
    </div>
{% endblock %}