src/Entity/Forum.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\PrimaryKeyTrait;
use App\Repository\ForumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ForumRepository::class)]
#[UniqueEntity('slug')]
class Forum
{
    use PrimaryKeyTrait;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?string $title = null;

    #[Gedmo\Slug(fields: ['title'])]
    #[ORM\Column(unique: true)]
    private ?string $slug = null;

    #[ORM\Column(nullable: true)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'forums')]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'forums')]
    private ?Forum $parent = null;

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: self::class)]
    #[ORM\OrderBy(['position' => 'ASC'])]
    private Collection $forums;

    #[ORM\Column(type: 'smallint')]
    #[Assert\NotBlank]
    #[Assert\Positive]
    private ?int $position = null;

    #[ORM\Column]
    #[Assert\NotNull]
    private bool $isLock = false;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Message $lastMessage = null;

    #[ORM\OneToMany(mappedBy: 'forum', targetEntity: Thread::class, orphanRemoval: true)]
    private Collection $threads;

    #[ORM\Column(type: 'smallint')]
    private int $totalThreads = 0;

    #[ORM\Column(type: 'smallint')]
    private int $totalMessages = 0;

    public function __construct()
    {
        $this->forums = new ArrayCollection();
        $this->threads = new ArrayCollection();
    }

    public function getRootCategory(): ?Category
    {
        if (null !== ($parent = $this->getParent())) {
            return $parent->getRootCategory();
        }

        return $this->getCategory();
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getForums(): Collection
    {
        return $this->forums;
    }

    public function addForum(self $forum): self
    {
        if (!$this->forums->contains($forum)) {
            $this->forums[] = $forum;
            $forum->setParent($this);
        }

        return $this;
    }

    public function removeForum(self $forum): self
    {
        if ($this->forums->removeElement($forum)) {
            // set the owning side to null (unless already changed)
            if ($forum->getParent() === $this) {
                $forum->setParent(null);
            }
        }

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function isLock(): bool
    {
        return $this->isLock;
    }

    public function setLock(bool $isLock): self
    {
        $this->isLock = $isLock;

        return $this;
    }

    public function getLastMessage(): ?Message
    {
        return $this->lastMessage;
    }

    public function setLastMessage(?Message $lastMessage): self
    {
        $this->lastMessage = $lastMessage;

        return $this;
    }

    /**
     * @return Collection|Thread[]
     */
    public function getThreads(): Collection
    {
        return $this->threads;
    }

    public function getTotalThreads(): int
    {
        $totalThreads = $this->totalThreads;

        foreach ($this->forums as $forum) {
            $totalThreads += $forum->getTotalThreads();
        }

        return $totalThreads;
    }

    public function incrementTotalThreads(): self
    {
        ++$this->totalThreads;

        if (null !== ($parent = $this->getParent())) {
            return $parent->incrementTotalThreads();
        }

        return $this;
    }

    public function decrementTotalThreads(): self
    {
        --$this->totalThreads;

        if (null !== ($parent = $this->getParent())) {
            return $parent->decrementTotalThreads();
        }

        return $this;
    }

    public function getTotalMessages(): int
    {
        $totalMessages = $this->totalMessages;

        foreach ($this->forums as $forum) {
            $totalMessages += $forum->getTotalMessages();
        }

        return $totalMessages;
    }

    public function incrementTotalMessages(): self
    {
        ++$this->totalMessages;

        return $this;
    }

    public function decrementTotalMessages(): self
    {
        --$this->totalMessages;

        return $this;
    }

    public function addThread(Thread $thread): self
    {
        if (!$this->threads->contains($thread)) {
            $this->threads[] = $thread;
            $thread->setForum($this);
        }

        return $this;
    }

    public function removeThread(Thread $thread): self
    {
        if ($this->threads->removeElement($thread)) {
            // set the owning side to null (unless already changed)
            if ($thread->getForum() === $this) {
                $thread->setForum(null);
            }
        }

        return $this;
    }
}

src/Entity/Thread.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\CreatedAtTrait;
use App\Entity\Traits\PrimaryKeyTrait;
use App\Repository\ThreadRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ThreadRepository::class)]
#[UniqueEntity('slug')]
class Thread
{
    use CreatedAtTrait;
    use PrimaryKeyTrait;

    final public const TITLE_MIN_LENGTH = 12;
    final public const TITLE_MAX_LENGTH = 50;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?string $title = null;

    #[Gedmo\Slug(fields: ['title'])]
    #[ORM\Column(unique: true)]
    private ?string $slug = null;

    #[Gedmo\Blameable(on: 'create')]
    #[ORM\ManyToOne(inversedBy: 'threads')]
    private ?User $author = null;

    #[ORM\ManyToOne(inversedBy: 'threads')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotNull]
    private ?Forum $forum = null;

    #[ORM\Column]
    #[Assert\NotNull]
    private bool $isLock = false;

    #[ORM\Column]
    #[Assert\NotNull]
    private bool $isPin = false;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Message $lastMessage = null;

    #[ORM\OneToMany(mappedBy: 'thread', targetEntity: Message::class, orphanRemoval: true)]
    private Collection $messages;

    #[ORM\Column(type: 'smallint')]
    private int $totalMessages = 0;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getForum(): ?Forum
    {
        return $this->forum;
    }

    public function setForum(?Forum $forum): self
    {
        $this->forum = $forum;

        return $this;
    }

    public function isLock(): bool
    {
        return $this->isLock;
    }

    public function setLock(bool $isLock): self
    {
        $this->isLock = $isLock;

        return $this;
    }

    public function isPin(): bool
    {
        return $this->isPin;
    }

    public function setPin(bool $isPin): self
    {
        $this->isPin = $isPin;

        return $this;
    }

    public function getLastMessage(): ?Message
    {
        return $this->lastMessage;
    }

    public function setLastMessage(?Message $lastMessage): self
    {
        $this->lastMessage = $lastMessage;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setThread($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getThread() === $this) {
                $message->setThread(null);
            }
        }

        return $this;
    }

    public function getTotalMessages(): ?int
    {
        return $this->totalMessages;
    }

    public function getTotalAnswers(): ?int
    {
        return $this->totalMessages - 1;
    }

    public function incrementTotalMessages(): self
    {
        ++$this->totalMessages;

        return $this;
    }

    public function decrementTotalMessages(): self
    {
        --$this->totalMessages;

        return $this;
    }
}

src/Controller/ForumController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Forum;
use App\Repository\CategoryRepository;
use App\Repository\ForumRepository;
use App\Repository\MessageRepository;
use App\Repository\ThreadRepository;
use App\Repository\UserRepository;
use App\Service\ForumService;
use App\Service\OptionService;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\DecoderInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route(path: '/forums')]
class ForumController extends AbstractBaseController
{
    public function __construct(private readonly RequestStack $requestStack, private readonly DecoderInterface $decoder, private readonly TranslatorInterface $translator)
    {
        parent::__construct($requestStack, $this->decoder);
    }

    #[Route(path: '/', name: 'forum.index', methods: ['GET'])]
    public function index(CategoryRepository $categoriesRepo, UserRepository $userRepository, MessageRepository $messageRepository, ThreadRepository $threadRepository, OptionService $optionService): Response
    {
        return $this->render('pages/forums.html.twig', [
            'categories' => $categoriesRepo->findAllCategories(),
            'onlineUsers' => $userRepository->findOnlineUsers(),
            'maxOnlineUsers' => $optionService->get('max_online_users', '0'),
            'maxOnlineUsersDate' => $optionService->get('max_online_users_date'),
            'nbUsers' => $userRepository->count([]),
            'lastRegistered' => $userRepository->findLastRegistered(),
            'nbMessages' => $messageRepository->count([]),
            'nbThreads' => $threadRepository->count([]),
        ]);
    }

    #[Route(path: '/{slug}', name: 'forum.show', requirements: ['id' => '\d+', 'slug' => '[\w\-_]+?$'], methods: ['GET'])]
    public function show(Forum $forum, ThreadRepository $threadRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $threadRepository->findThreadsByForumQb($forum),
            $request->query->getInt('page', 1),
            15
        );

        return $this->render('forum/show.html.twig', [
            'forum' => $forum,
            'pagination' => $pagination,
        ]);
    }

    #[Route(path: '/c/{slug}', name: 'category.show', requirements: ['slug' => '^(?:[^\d])[\w\-_]+?$'], methods: ['GET'])]
    public function category(Category $category, ForumRepository $forumRepository): Response
    {
        return $this->render('forum/category.html.twig', [
            'category' => $category,
            'forums' => $forumRepository->findForumsByCategory($category),
        ]);
    }

    #[IsGranted('LOCK', subject: 'forum')]
    #[Route(path: '/{slug}/lock', name: 'forum.lock', methods: ['GET'])]
    public function lock(Forum $forum, ForumService $forumService): Response
    {
        $forumService->lock($forum);
        $this->addCustomFlash('success', $this->translator->trans('Forum'), $this->translator->trans('The forum has been locked'));

        return $this->redirectToRoute('forum.show', [
            'slug' => $forum->getSlug(),
        ]);
    }

    #[IsGranted('LOCK', subject: 'forum')]
    #[Route(path: '/{slug}/unlock', name: 'forum.unlock', methods: ['GET'])]
    public function unlock(Forum $forum, ForumService $forumService): Response
    {
        $forumService->unlock($forum);
        $this->addCustomFlash('success', $this->translator->trans('Forum'), $this->translator->trans('The forum has been unlocked'));

        return $this->redirectToRoute('forum.show', [
            'slug' => $forum->getSlug(),
        ]);
    }
}

templates/forums/category.html.twig
{% extends 'layouts/full-width.html.twig' %}

{% block title %}{{ category.title }}{% endblock %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('forums.index') }}">Forums</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ category.title }}</li>
        </ol>
    </nav>

    <div class="card bg-secondary mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-8">{{ category.title }}</div>
                <div class="col-lg-2 col-md-3 col-sm-4 d-none d-sm-block text-center">SUJETS</div>
                <div class="col-lg-2 col-md-3 d-none d-md-block text-center">MESSAGES</div>
                <div class="col-lg-3 d-none d-lg-block">DERNIER MESSAGE</div>
            </div>
        </div>

        {% for forum in forums %}
            {{ include('forums/_forum_card.html.twig') }}
        {% endfor %}
    </div>
{% endblock %}

templates/forums/forum.html.twig
{% extends 'layouts/modnav.html.twig' %}

{% block title %}{{ forum.title }}{% endblock %}

{% block modnav_elements %}
    {{ include('forums/modnav.html.twig') }}
{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="container">
        <div class="row justify-content-md-center mt-5">
            <div class="col col-lg-12 col-md-12 col-sm-12">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ path('forums.index') }}">Forums</a></li>
                        {% for part in forum|breadcrumb %}
                            {% if loop.last %}
                                <li class="breadcrumb-item active" aria-current="page">{{ part.title }}</li>
                            {% else %}
                                <li class="breadcrumb-item"><a href="{{ part.url }}">{{ part.title }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ol>
                </nav>

                <div class="card bg-secondary mb-4">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">{{ forum.title }}</div>
                            {% if forum.forums|length > 0 %}
                                <div class="col-lg-2 col-md-3 col-sm-4 d-none d-sm-block text-center">SUJETS</div>
                                <div class="col-lg-2 col-md-3 d-none d-md-block text-center">MESSAGES</div>
                                <div class="col-lg-3 d-none d-lg-block">DERNIER MESSAGE</div>
                            {% else %}
                                <div class="col-lg-2 col-md-3 col-sm-4 d-none d-sm-block text-center">PAR</div>
                                <div class="col-lg-2 col-md-3 d-none d-md-block text-center">REPONSES</div>
                                <div class="col-lg-4 d-none d-lg-block">DERNIER MESSAGE</div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body">
                        {% for subforum in forum.forums %}
                        {{ loop.first ? '<div class="row">' : '<div class="row mt-4">' }}
                        <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">
                            <h5 class="card-title">
                                <a href="{{ path('forum.show', {'slug': subforum.slug}) }}">{{ subforum.title }}</a>
                            </h5>
                            <p class="card-text">{{ subforum.description }}</p>
                        </div>
                        <div class="col-lg-2 col-md-3 col-sm-4 d-none d-sm-block text-center">{{ subforum.totalThreads }}</div>
                        <div class="col-lg-2 col-md-3 d-none d-md-block text-center">{{ subforum.totalMessages }}</div>
                        <div class="col-lg-4 d-none d-lg-block">
                            {% if subforum.lastMessage %}
                                {% set last_message = subforum.lastMessage %}

                                <a href="{{ message_link(last_message) }}">{{ last_message.publishedAt|ago }}</a>
                                par {{ user_profile_link(last_message.author) }}
                            {% else %}
                                Aucun message
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}

                    {% if forum.forums|length > 0 %}
                        <div class="row mt-3">
                            <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12"></div>
                            <div class="col-lg-2 col-md-3 col-sm-4 d-none d-sm-block text-center">
                                <h5>PAR</h5>
                            </div>
                            <div class="col-lg-2 col-md-3 d-none d-md-block text-center">
                                <h5>REPONSES</h5>
                            </div>
                            <div class="col-lg-4 d-none d-lg-block">
                                <h5>DERNIER MESSAGE</h5>
                            </div>
                        </div>
                    {% endif %}

                    {% for thread in threads %}
                        <div class="row mb-1">
                            <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">
                                {{ thread.pin ? '<i class="fas fa-thumbtack"></i>' }}
                                {{ thread.lock ? '<i class="fas fa-lock"></i>' }}
                                <a href="{{ path('thread.show', {'slug': thread.slug}) }}">{{ thread.title }}</a>
                            </div>
                            <div class="col-lg-2 col-md-3 col-sm-4 d-none d-sm-block text-center">
                                {{ user_profile_link(thread.author) }}
                            </div>
                            <div class="col-lg-2 col-md-3 d-none d-md-block text-center">{{ thread.getTotalAnswers }}</div>
                            <div class="col-lg-4 d-none d-lg-block">
                                {% set last_message = thread.lastMessage %}

                                <a href="{{ message_link(last_message) }}">{{ last_message.publishedAt|ago }}</a>
                                par {{ user_profile_link(last_message.author) }}
                            </div>
                        </div>
                    {% else %}
                        Ce forum ne dispose pas encore de sujets.
                    {% endfor %}
                </div>
            </div>
            {% if forum.lock == false and is_granted('ROLE_USER') %}
                <a class="mb-3 btn btn-primary" href="{{ path('thread.new', {'slug': forum.slug}) }}">Nouveau sujet</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/forums/message_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition de votre message{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-md-center mt-5">
            <div class="col col-lg-12 col-md-12 col-sm-12">
                <div class="mb-3">
                    <p class="text-center">
                        Edition de votre message dans le sujet {{ message.thread.title }}
                    </p>
                    {{ include('forums/_form_message.html.twig', {button_label: 'Modifier'}) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/forums/thread.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ thread.title }} par {{ thread.author.pseudo }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-md-center mt-5">
            <div class="col col-lg-12 col-md-12 col-sm-12">

                {% for message in messages %}
                    <div class="card bg-secondary mb-4 d-flex" id="{{ message.id }}">
                        <div class="card-header">{{ thread.title }}</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-2 text-center">
                                    {% set author = message.author %}
                                    {% if author is null %}
                                        Compte supprimé
                                    {% else %}
                                        {{ user_profile_link(message.author) }}

                                        {% set role = user_profile_role(author) %}
                                        {{ role ? role }}
                                    {% endif %}
                                </div>
                                <div class="col-lg-10">{{ message.content|purify }}</div>
                            </div>

                            <div class="row mt-3">
                                <div class="col text-right">
                                    Posté le {{ message.publishedAt|date('d/m/Y à H:i:s') }}
                                    {% if (message.author == app.user) and (message.thread.locked) is null %}
                                        - <a href="{{ path('message.edit', {'id': message.id}) }}">Editer</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                {% if not thread.locked %}
                    {% if app.user %}
                        <div class="mb-3">
                            <p class="text-center">
                                Connecté en tant que {{ app.user.pseudo }}, vous pouvez répondre :
                            </p>
                            {% include 'forums/_form_message.html.twig' %}
                        </div>
                    {% else %}
                        <div class="alert alert-info text-center">
                            <a href="{{ path('security.login') }}">Connectez-vous pour répondre.</a>
                        </div>
                    {% endif %}
                {% else %}
                    {% if app.user %}
                        <div class="alert alert-warning text-center">Ce sujet est verrouillé, vous ne pouvez donc pas y
                            répondre.
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}